import { JSDOM } from 'jsdom';
const dom = new JSDOM('<!doctype html><html><body></body></html>');
globalThis.window = dom.window; globalThis.document = dom.window.document;
const mermaid = (await import('mermaid')).default;
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });
const src = 'flowchart LR\n  subgraph sg1 [Group A]\n    A[Start] & B(Proc) --> C{Dec}\n  end\n  C -->|yes| D[(DB)]\n  C -.->|no| E>Flag]\n  classDef warn fill:#f96\n  class A warn';
await mermaid.parse(src);
const db = (await mermaid.mermaidAPI.getDiagramFromText(src)).db;
console.log('keys:', Object.keys(db).filter(k=>k.startsWith('get')).join(','));
for (const [k,x] of db.getVertices()) console.log('V', k, JSON.stringify({label:x.label, type:x.type, classes:x.classes, styles:x.styles}));
for (const e of db.getEdges()) console.log('E', JSON.stringify(e));
console.log('subgraphs:', JSON.stringify(db.getSubGraphs()));
console.log('classes:', JSON.stringify([...db.getClasses().entries()]));
console.log('direction:', db.getDirection());
